# Generated by Django 5.0.6 on 2024-05-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
            preserve_default=False,
        ),
    ]
