# Generated by Django 5.0.6 on 2024-07-02 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_sheen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sheen',
        ),
    ]
