# Generated by Django 5.0.6 on 2024-06-07 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_deliveryaddress_user'),
        ('products', '0010_alter_productspage_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productsize'),
            preserve_default=False,
        ),
    ]
