# Generated by Django 5.0.6 on 2024-06-11 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_shippingoption_products_shipping_options'),
        ('user', '0002_alter_order_product_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.shippingoption'),
        ),
    ]
