# Generated by Django 5.0.6 on 2024-05-18 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_desciption_products_description_productspage_and_more'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingvideo',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
