# Generated by Django 5.0.6 on 2024-05-16 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='desciption',
            new_name='description',
        ),
        migrations.CreateModel(
            name='ProductsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('shipping', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('order_image', models.ImageField(blank=True, null=True, upload_to='order_images')),
                ('buy_with_items', models.ManyToManyField(blank=True, related_name='bought_with', to='products.products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductPage',
        ),
    ]
