# Generated by Django 5.0.6 on 2024-06-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_section_remove_products_comparison_chart_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='comparison_chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='comparison_images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='comparison_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
