# Generated by Django 5.0.6 on 2024-05-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspage',
            name='order_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products/'),
        ),
    ]
