# Generated by Django 5.0.6 on 2024-06-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_color_remove_products_color_products_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='colors',
        ),
        migrations.AddField(
            model_name='products',
            name='sheens',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.sheen'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
