# Generated by Django 5.0.6 on 2024-06-07 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_products_image_productimage_productsize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='default_price',
        ),
    ]
