# Generated by Django 5.0.6 on 2024-06-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productspage_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='shipping_options',
            field=models.ManyToManyField(related_name='products', to='products.shippingoption'),
        ),
    ]
