# Generated by Django 5.0.6 on 2024-06-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_shippingoption_products_shipping_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspage',
            name='comparison_chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products/'),
        ),
    ]
