# Generated by Django 5.0.6 on 2024-06-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productspage_comparison_chart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspage',
            name='comparison_chart_image',
        ),
        migrations.AddField(
            model_name='products',
            name='comparison_chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/products/comparison_charts/'),
        ),
    ]
