# Generated by Django 5.0.6 on 2024-06-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productspage_comparison_chart_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='comparison_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
